#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from src.blog_to_twitter.configuration import Configuration
from src.blog_to_twitter.reader import Reader
from src.blog_to_twitter.twbot import TwBot

if __name__ == '__main__':
    conf = Configuration()

    twBot = TwBot(
        conf.consumer_key(),
        conf.consumer_secret(),
        conf.access_token(),
        conf.access_token_secret()
    )

    reader = Reader(conf.uri())

    entries = reader.new_entries(days=conf.days())

    print('Announce in twitter articles published in {} in the last {} days.'.format(conf.name(), conf.days()))
    print('-' * 80)
    for entry in entries:
        message = 'Publicado el artículo: {} {}'.format(entry.title, entry.link)
        print(message)
        twBot.say(message)
    else:
        print('-' * 80)
        print('Finished.')

    exit(0)