#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from src.blog_to_twitter.configuration import Configuration
from src.blog_to_twitter.clioptions import CliOptions
from src.blog_to_twitter.publisher import Publisher
from src.blog_to_twitter.reader import Reader
from src.blog_to_twitter.twbot import TwBot

if __name__ == '__main__':
    conf = None
    options = CliOptions()

    try:
        conf = Configuration(options)
    except Exception as e:
        print(e)
        exit(1)

    twitter_bot = TwBot(
        conf.consumer_key(),
        conf.consumer_secret(),
        conf.access_token(),
        conf.access_token_secret()
    )

    reader = Reader(conf.uri())

    publisher = Publisher(reader, twitter_bot, conf, options)

    publisher.get_and_publish_posts()

    exit(0)
